# Generated by Django 2.0.6 on 2018-10-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='values_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_flux', models.DecimalField(decimal_places=6, max_digits=30)),
                ('vapor_flux', models.DecimalField(decimal_places=6, max_digits=30)),
                ('liquid_density', models.DecimalField(decimal_places=6, max_digits=30)),
                ('vapor_density', models.DecimalField(decimal_places=6, max_digits=30)),
                ('API', models.DecimalField(decimal_places=6, max_digits=30)),
            ],
        ),
    ]
